### ISSUE TITLE
Installation of ScratchAPI problems

### ISSUE THREAD

**Issue by 03172008** [Snipet/scratchBot#10]
The command

`pip install scratchapi`

is outdated, I believe. How do I install ScratchAPI now?

**Comment by BonfireScratch** [comment]
@03172008 haven't worked on this for a while. I am going to look into it.

**Comment by 03172008** [comment]
Thanks!

**Comment by BonfireScratch** [comment]
@03172008 it works fine for me... What is your Python version and OS? If you use Python 3 try using `pip3` and see if it works. Unfortunately, I am not sure whether this code will work in Python 2...

**Comment by 03172008** [comment]
do you mean pip3 install scratchapi? I am using windows 10, and i think that I have python 3. I will check and update it if it's not. Which instructions did you follow? The ones in the wiki, or the ones in the readme?

**Comment by BonfireScratch** [comment]
@03172008 I just tried to manually install it by using `pip3 install scratchapi`. The instructions in the wiki are outdated and have stopped working. Use the ones in the README.

**Comment by 03172008** [comment]
ok. Do I need scratchapi though?

**Comment by BonfireScratch** [comment]
You do; it is listed in the `requirements.txt` file. If you follow the instructions in the README all dependencies will automatically be installed for you, so there's nothing to worry about as long as the `pip` command works fine.

**Comment by 03172008** [comment]
If I get this working, what are the commands that can be used?

**Comment by BonfireScratch** [comment]
To install `scratchapi` only you can do `pip3 install scratchapi`. To install all dependencies follow the instructions in the README.
