### ISSUE TITLE
My username doesn't pass

### ISSUE THREAD

**Issue by locness3** [Snipet/scratchBot#6]
**Describe the bug**
I launch the bot using launcher.py. It asks me for username. I type "Locness". It says :

```
Traceback (most recent call last):
  File "launcher.py", line 79, in <module>
    main()
  File "launcher.py", line 75, in main
    askForData()
  File "launcher.py", line 42, in askForData
    user = input("Enter the bot's username > ")
  File "<string>", line 1, in <module>
NameError: name 'Locness' is not defined

```
If I try to run it again it does nothing expect if i remove the version.json file.

**Expected behavior**
I except it, to well... work.

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Version: stretch

**Additional context**
BTW, you should add Python version field to your issue template (in desktop)

**Comment by BonfireScratch** [comment]
@locness3 I can't reproduce the bug. What is your Python version?

**Comment by locness3** [comment]
2.7.13 I guess, but I did updates and I don't remember if I tested this before or after the updates. I will try running it again.

**Comment by locness3** [comment]
still happens.

**Comment by BonfireScratch** [comment]
@locness3 The ScratchBot is designed for Python 3

**Comment by BonfireScratch** [comment]
@locness3 Try another username and tell me the output

**Comment by locness3** [comment]
> @locness3 Try another username and tell me the output

Same with BledGames account. Gonna change my python version.

**Comment by BonfireScratch** [comment]
@locness3 sometimes errors occur because of a version being 64-bit.

**Comment by locness3** [comment]
I have 2.7 and 3.5 co-existing. I'm re-installing pip modules and trying with `python3.5`.

**Comment by BonfireScratch** [comment]
@locness3 do you have any other platforms to test with?

**Comment by locness3** [comment]
> @locness3 do you have any other platforms to test with?

nope. Please wait while I figure out how to install pip packages for 3.5.

**Comment by locness3** [comment]
[Found out!](https://stackoverflow.com/questions/2812520/dealing-with-multiple-python-versions-and-pip)

**Comment by locness3** [comment]
It works, now that I installed packages for python 3.5, you may say something about that in README.

**Comment by BonfireScratch** [comment]
@locness3 like what?

**Comment by BonfireScratch** [comment]
@locness3 what should I write?

**Comment by locness3** [comment]
> @locness3 what should I write?

That, if multiple versions co-exist on one environement, people should use the command corresposnding to python 3 instead of the global python command, and also that packages should be installed using that same command followed by -m and pip command

**Comment by BonfireScratch** [comment]
@locness3 OK
