### ISSUE TITLE
Using requirements.txt

### ISSUE THREAD

**Issue by locness3** [Snipet/scratchBot#7]
**Describe the solution you'd like**
I'd like if you used a requirements.txt file for pip, so we can install all dependencies in one command.

**Comment by BonfireScratch** [comment]
@locness3 how can I do so?

**Comment by locness3** [comment]
I don't know, that's maybe on the pip docuemntation ?

**Comment by BonfireScratch** [comment]
@BonfireScratch OK

**Comment by BonfireScratch** [comment]
@locness3 Does it work now?

**Comment by locness3** [comment]
> @locness3 Does it work now?

Wrong issue

**Comment by BonfireScratch** [comment]
@locness3 Not really. Could you uninstall the packages and reinstall them using the `requirements.txt` file?

**Comment by locness3** [comment]
> @locness3 Not really. Could you uninstall the packages and reinstall them using the `requirements.txt` file?

idk how to uninstall, sorry

**Comment by BonfireScratch** [comment]
@locness3 [Try this](https://pip.pypa.io/en/stable/reference/pip_uninstall/)
