### ISSUE TITLE
Don't store passwords in clear text

### ISSUE THREAD

**Issue by locness3** [Snipet/scratchBot#8]
You should encrypt passwords when storing them, and hide the key.

**Comment by BonfireScratch** [comment]
@locness3 I'll see. But I won't use any serious encryption. Only a cipher.

**Comment by BonfireScratch** [comment]
@locness3 I don't think one is needed, as the files are private

**Comment by locness3** [comment]
> @locness3 I don't think one is needed, as the files are private

If someone accesses your computer ? Or you're "hosting" the thing and passwords are leaked ?

**Comment by BonfireScratch** [comment]
@locness3 I'm no cryptologist, and if somebody were to access your computer, they probably wouldn't care about your Scratch account

**Comment by locness3** [comment]
> @locness3 I'm no cryptologist

An encryption library isn't hard to use.

> , and if somebody were to access your computer, they probably wouldn't care about your Scratch account

Why is the Scratch Team putting this in browser console then ?

![Screen Shot 2019-05-25 at 15 37 53](https://user-images.githubusercontent.com/37651007/58370124-21c99800-7f03-11e9-93bd-2ec01e83708a.png)
Somebody *could* be interested in it.

**Comment by BonfireScratch** [comment]
@locness3
> An encryption library isn't hard to use.
Could you help me with that?

**Comment by locness3** [comment]
> @locness3
> 
> > An encryption library isn't hard to use.
> 
> Could you help me with that?

Well, read docs, I don't have advise...

**Comment by locness3** [comment]
https://pypi.org/project/pycrypto/

**Comment by BonfireScratch** [comment]
@locness3 I am unable to do that now, so this will have to wait for a few days

**Comment by locness3** [comment]
> @locness3 I am unable to do that now, so this will have to wait for a few days

Please reopen the issue so.

**Comment by BonfireScratch** [comment]
Done!

**Comment by BonfireScratch** [comment]
@locness3 could you test the encrypting please?

**Comment by locness3** [comment]
Trying that now

**Comment by locness3** [comment]
Re-installed everything (even source code), the install takes a lot more time, I run the thing, and...
```
Traceback (most recent call last) :
  File "launcher.py", line 4, in <module>
    import encryptor
importError: No module named "encrytpor"

```

**Comment by BonfireScratch** [comment]
@locness3 aw yes!

**Comment by locness3** [comment]
BTW you should be descriptive in your commit messages

**Comment by BonfireScratch** [comment]
@locness3 OK!

**Comment by BonfireScratch** [comment]
@locness3 It should work now. But how can I hide the key?

**Comment by locness3** [comment]
> @locness3 It should work now. But how can I hide the key?

Idk, maybe use a random key, and store it in an unexpected place ? Google it.
But I can't test for now since I don't have my Raspberry pi for now.

**Comment by BonfireScratch** [comment]
@locness3 OK

**Comment by BonfireScratch** [comment]
@locness3

**Comment by locness3** [comment]
Yeah I should be able to do it an half an hour or more.

**Comment by BonfireScratch** [comment]
@locness3 lol

**Comment by locness3** [comment]
Oh yeah!

**Comment by locness3** [comment]
BTW (that's off-topic), I have thought of a product : a github app, which, per-repo, has a "ping thread", and so people /ping somone in an issue, and the bot posts to that thread and deletes the invocation.

**Comment by locness3** [comment]
```
pi@raspberrypi:~/scratchBot/src $ python3.5 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 76, in <module>
    main()
  File "launcher.py", line 72, in main
    j["version"] = mostRecentVersion
UnboundLocalError: local variable 'j' referenced before assignment

```

**Comment by BonfireScratch** [comment]
@locness3 what about it now?

**Comment by locness3** [comment]
> @locness3 what about it now?

Please test it by yourself as I can't test it for now.

**Comment by BonfireScratch** [comment]
@BonfireScratch I can't either

**Comment by locness3** [comment]
@Snipet ?

**Comment by locness3** [comment]
In fact, you should test your changes before pushing them to the master branch. That's not good practice.

**Comment by BonfireScratch** [comment]
@locness3 These days I don't have the time to, as my father uses the computer for 6-7 hours a day

**Comment by locness3** [comment]
> @locness3 These days I don't have the time to, as my father uses the computer for 6-7 hours a day

So, don't push directly to the master branch. Use another branch, the feature's made for that.

**Comment by BonfireScratch** [comment]
@locness3 great idea!

**Comment by locness3** [comment]
> @locness3 great idea!

Not to be mean or whatever, but that is one of git's basic concepts. That's not a "great idea".

**Comment by BonfireScratch** [comment]
@locness3 you are not mean!

**Comment by BonfireScratch** [comment]
@SimpleBinary do you have any ideas? You have far more knowledge than we do

**Comment by BonfireScratch** [comment]
@locness3 is adding a simple cipher to the key a satisfactory solution?

**Comment by locness3** [comment]
> @locness3 is adding a simple cipher to the key a satisfactory solution? This is actually the best solution I have found!

idk

**Comment by BonfireScratch** [comment]
@locness3 do you have any better ideas?

**Comment by locness3** [comment]
> @locness3 do you have any better ideas?

I don't know anything about cryptography. Truly sorry.

**Comment by BonfireScratch** [comment]
@locness3 

> I don't know anything about cryptography. Truly sorry.

Me neither... Do you know somebody who can help?

**Comment by locness3** [comment]
Go on some forums

**Comment by BonfireScratch** [comment]
@locness3 closing it for now...

**Comment by SimpleBinary** [comment]
@BonfireScratch What type of cipher are you planning to use?

**Comment by BonfireScratch** [comment]
@SimpleBinary re-encoding the key and store the key for the original key
