### ISSUE TITLE
First readme command seems wrong

### ISSUE THREAD

**Issue by locness3** [Snipet/scratchBot#9]
People should clone/download the repo and execute `pip install -r requirements.txt`.

**Comment by BonfireScratch** [comment]
OK

**Comment by BonfireScratch** [comment]
@locness3 is it correct now?

**Comment by BonfireScratch** [comment]
@locness3

**Comment by locness3** [comment]
yeah

**Comment by locness3** [comment]
But it didn't work for me. provide the alternative command to install packages spearately (what you had at the start)

**Comment by BonfireScratch** [comment]
@locness3 do you know how to make a `requirements.txt ` file?

**Comment by locness3** [comment]
> @locness3 do you know how to make a `requirements.txt ` file?

From the command output it seemed correctly made, but the error was coming apparently from install script of a module. But no, idk how to do this, google it.

**Comment by BonfireScratch** [comment]
@locness3 It might be because I have not specified the versions of the libraries

**Comment by locness3** [comment]
¯\_(ツ)_/¯

**Comment by BonfireScratch** [comment]
@locness3 which library was it?

**Comment by locness3** [comment]
bs4 I think

**Comment by BonfireScratch** [comment]
@locness3 try again

**Comment by locness3** [comment]
> @locness3 try again

I don't have time. remind me in 24 hours.

**Comment by BonfireScratch** [comment]
@locness3

**Comment by locness3** [comment]
It works! 🎆

**Comment by locness3** [comment]
I tested it with `pip` , so it used python 2.7, but it also worked with `python3.5 -m pip` !
